### ISSUE TITLE
"pnpm run dev" is not wokring fine

### ISSUE THREAD

**Issue by suyash5053** [Vexilla/vexilla#26]
Already installed all the dependencies with pnpm, I too have turbo-cli globally,
But after running the `pnpm run dev`

```
git-auth:dev: Port 5173 is in use, trying another one...
git-auth:dev: Port 5174 is in use, trying another one...
git-auth:dev:
git-auth:dev:   VITE v4.3.5  ready in 1975 ms
git-auth:dev:
git-auth:dev:   ➜  Local:   http://localhost:5175/
git-auth:dev:   ➜  Network: use --host to expose
git-auth:dev:   ➜  press h to show help
@vexilla/cli:dev: /home/suyash/vexilla/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.8_typescript@5.0.4/node_modules/ts-node/src/index.ts:859
@vexilla/cli:dev:     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
@vexilla/cli:dev:            ^
@vexilla/cli:dev: TSError: ⨯ Unable to compile TypeScript:
@vexilla/cli:dev: src/utilities.ts:4:63 - error TS2307: Cannot find module '@vexilla/types' or its corresponding type declarations.
@vexilla/cli:dev:
@vexilla/cli:dev: 4 import { PublishedGroup, VexillaFlags, VexillaManifest } from "@vexilla/types";
@vexilla/cli:dev:                                                                 ~~~~~~~~~~~~~~~~
@vexilla/cli:dev: src/utilities.ts:22:34 - error TS7031: Binding element 'groupId' implicitly has an 'any' type.
@vexilla/cli:dev:
@vexilla/cli:dev: 22     manifest.groups.map(async ({ groupId }) => {
@vexilla/cli:dev:                                     ~~~~~~~
@vexilla/cli:dev:
@vexilla/cli:dev:     at createTSError (/home/suyash/vexilla/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.8_typescript@5.0.4/node_modules/ts-node/src/index.ts:859:12)
@vexilla/cli:dev:     at reportTSError (/home/suyash/vexilla/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.8_typescript@5.0.4/node_modules/ts-node/src/index.ts:863:19)
@vexilla/cli:dev:     at getOutput (/home/suyash/vexilla/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.8_typescript@5.0.4/node_modules/ts-node/src/index.ts:1077:36)
@vexilla/cli:dev:     at Object.compile (/home/suyash/vexilla/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.8_typescript@5.0.4/node_modules/ts-node/src/index.ts:1433:41)
@vexilla/cli:dev:     at Module.m._compile (/home/suyash/vexilla/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.8_typescript@5.0.4/node_modules/ts-node/src/index.ts:1617:30)
@vexilla/cli:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
@vexilla/cli:dev:     at Object.require.extensions.<computed> [as .ts] (/home/suyash/vexilla/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.8_typescript@5.0.4/node_modules/ts-node/src/index.ts:1621:12)
@vexilla/cli:dev:     at Module.load (node:internal/modules/cjs/loader:1207:32)
@vexilla/cli:dev:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
@vexilla/cli:dev:     at Module.require (node:internal/modules/cjs/loader:1235:19) {
@vexilla/cli:dev:   diagnosticCodes: [ 2307, 7031 ]
@vexilla/cli:dev: }
@vexilla/cli:dev:  ELIFECYCLE  Command failed with exit code 1.
@vexilla/cli:dev: ERROR: command finished with error: command (/home/suyash/vexilla/packages/cli) /home/linuxbrew/.linuxbrew/bin/pnpm run dev exited (1)
@vexilla/cli#dev: command (/home/suyash/vexilla/packages/cli) /home/linuxbrew/.linuxbrew/bin/pnpm run dev exited (1)
```

**Comment by suyash5053** [comment]
The issue got resolved,
## Not Sure about the problems, but it can be
- Outdated `node` version.
- Outdated `pnpm` version.
- Wrong node modules, because you ran `bun install` first without using the `pnpm install.`

## Steps to resolve
- Check your `pnpm, node` version, update if outdated.
- Check whether you have all the dependencies installed.
- Check whether you are running your dev command in right diredtory.
- If you have used `bun` before `pnpm`, try cloning the project again, and run `pnpm install`

**Comment by cmgriffing** [comment]
Recursively deleting the `node_modules` folders after using the wrong tool/command would be a step that could be taken instead of doing another clone.
